channels:
  - defaults
  - conda-forge
dependencies:
  - numpy>=1.20
  - pip>=20.3.3
  - python=3.9
  - h5py>=2.3.1
  - corner
  - pip:
      - matplotlib>=3.3.3
      - seaborn==0.11.2
      - tables==3.7.0
      - astropy==5.0.4
