; BackPop INI file

[BackPop]

; n_threads
; Sets the number of cores to use in multiprocessing
; 
; Options: 
;    integer values - Number of cores
;    1 - For example, this sets the number of cores to 1
; Default: 1
n_threads = 1

; n_eff
; Minimum effective sample size (see n_eff docs for more information)
; 
; Options: 
;    8000 - For example, this sets the minimum effective sample size to be 8000
; Default: 8000
n_eff = 8000

; n_live
; Number of live points (see '>n_live docs for more information)
; 
; Options: 
;    1000 - For example, this sets the number of live points to be 1000
; Default: 1000
n_live = 1000

; verbose
; Whether to print verbose output from BackPop and sampler.
; 
; Options: 
;    True - Print verbose output from BackPop and sampler progress.
;    False - Do not print verbose output from Backpop and sampler progress.
; Default: False
verbose = False

; output folder
; Path to save output files. If not supplied, output folder created in directory BackPop is run.
; 
; Options: 
;    path/to/output_folder - This specifies the absolute path to save the output files from BackPop.
;     - Default value (not supplying an output path)
; Default: ""
output folder = ""

; resume
; Resumes sampling from previous run (see `resume doc `_
; 
; Options: 
;    True - Resume sampler from previous run.
;    False - Do not resume sampler from previous run. Restart sampler and rewrite files.
; Default: False
resume = False

; use_bcm
; Saves BCM from Backpop run (see `bcm doc `_
; 
; Options: 
;    True - Saves BCM from BackPop run.
;    False - Does not save BCM from backpop run.
; Default: False
use_bcm = False

[observables]

; sampling_method
; Select which models to use to generate an initial sample of binary parameters at Zero Age Main Sequence
; 
; Options: 
;    independent - Initialize binaries with independent parameter distributions for the primary mass, mass ratio, eccentricity, separation, and binary fraction
; Default: independent
sampling_method = independent

[priors]

; convergence_params
; A list of parameters you would like to verify have converged to a single distribution shape when running cosmic-pop from the command line.
; 
; Options: 
;    mass_1 - Primary mass
; Default: [mass_1]
convergence_params = [mass_1]

[sse]

; stellar_engine
; Select which stellar evolution engine to use for single star evolution
; 
; Options: 
;    sse - Use SSE for single star evolution which will apply the fitting formulae from Hurley+2000 for the single star evolution
;    metisse - Use METISSE for single star evolution, must supply ``path_to_tracks`` and ``path_to_he_tracks``
; Default: sse
stellar_engine = sse

; path_to_tracks
; Path to the METISSE tracks for single star evolution. Must be supplied if ``stellar_engine`` is set to ``metisse``
; 
; Options: 
;    path/to/tracks - This specifies the absolute path to the EEP tracks for single star evolution. Leave the string empty if not using METISSE for single star evolution.
;     - Default value (not using METISSE for single star evolution)
; Default: ""
path_to_tracks = ""

; path_to_he_tracks
; Path to the METISSE tracks for helium star evolution. Must be supplied if ``stellar_engine`` is set to ``metisse``
; 
; Options: 
;    path/to/he_tracks - This specifies the absolute path to the EEP tracks for helium star evolution. Leave the string empty if not using METISSE for single star evolution.
;     - Default value (not using METISSE for single star evolution)
; Default: ""
path_to_he_tracks = ""

; z_accuracy_limit
; Sets the maximum allowed relative difference between the supplied metallicity and the tracks used by METISSE. If cosmic throws an error due to metallicity, increasing this slightly may help. Must be supplied if ``stellar_engine`` is set to ``metisse``
; 
; Options: 
;    positive values - Minimum metallicity
;    0.01 - Recommended value
; Default: 0.01
z_accuracy_limit = 0.01

; metisse_verbose
; Whether to print verbose output from METISSE when using METISSE for single star evolution.
; 
; Options: 
;    True - Print verbose output from METISSE when using METISSE for single star evolution.
;    False - Do not print verbose output from METISSE when using METISSE for single star evolution.
; Default: False
metisse_verbose = False
